### ISSUE TITLE
KafkaListener OffsetStrategy.DISABLED Manual Acknowledgement Failure (Reactive Type)

### ISSUE THREAD

**Issue by brianwyka** [micronaut-projects/micronaut-kafka#103]
With a `@KafkaListener` that has offset strategy diabled, when using the reactive approach, the `Acknowledgement.ack()` produces an exception when called within the `@KafkaListener`.

```java
@KafkaListener(groupId = "archive-upload", offsetStrategy = OffsetStrategy.DISABLED)
public class ArchiveUploadMessageProcessor {

    private final ArchiveService archiveService;

    @Topic("${kafka-topics.archive-upload}")
    public Single<String> processMessage(@Body final PayloadArchiveUploadMessage payloadArchiveUploadMessage, final Acknowledgement acknowledgement) {
        val payloadKey = payloadArchiveUploadMessage.getPayloadRequest().getPayloadKey();
        val payloadKeyString = PayloadKeyFormatter.asString(payloadKey);
        return archive(payloadArchiveUploadMessage, payloadKeyString, acknowledgement)
                .doOnSuccess(payloadUrl -> acknowledgement.ack());
    }
```

Below is the exception:

```txt
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
```

My assumption is the error is triggered from the lambda implementation of `Acknowledgement` below in `KafkaConsumerProcessor`:

https://github.com/micronaut-projects/micronaut-kafka/blob/0d9f891e7fb6867b4196f4bf3508b5628ba9a815/kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java#L488-L492

Relevant consumer thread configuration:

```yaml
micronaut:
  executors:
    consumer:
      type: fixed
      nThreads: ${KAFKA_CONSUMER_THREAD_COUNT:4}
```

**Comment by brianwyka** [comment]
Perhaps its happening in a different thread since its chained in the reactive stream?

**Comment by brianwyka** [comment]
After reading around the documentation a bit, I was able to find this:

> Alternatively, you can use the @Blocking annotation to tell Micronaut to subscribe to the returned reactive type in a blocking manner which will result in blocking the poll loop, preventing offsets from being committed automatically:

After adding the `@Blocking` annotation, its working as expected, however, kind of defeats the purpose of using reactive style of programming in the first place.  Any way this can be achieved without `@Blocking` annotation on the kafka listener?

**Comment by ctoestreich** [comment]
@brianwyka Not sure that it will change the exception, but are you trying to bee reactive on the way IN or the way OUT or both?  Just writing pseudo code here from your above example.

```java
 public Single<String> processMessage(@Body final Single<PayloadArchiveUploadMessage> payloadArchiveUploadMessage, final Acknowledgement c) {
        payloadArchiveUploadMessage.doOnSuccess((payload) -> 
        val payloadKey = payload.getPayloadRequest().getPayloadKey();
        val payloadKeyString = PayloadKeyFormatter.asString(payloadKey);
        archive(payloadArchiveUploadMessage, payloadKeyString, acknowledgement)
        acknowledgement.ack();
    }
```

Also should you synchronize the method?

**Comment by graemerocher** [comment]
Kafka consumers are inherently single threaded so you have to always acknowledge the message on the same thread as the listener executed on. That means waiting for all other publishers to complete

**Comment by brianwyka** [comment]
@graemerocher is there any way to bind a method argument which would be a callback to the publishers being completed which is a `Supplier<KafkaConsumer>` or `Supplier`Acknowledgement` that way it can be executed at the appropriate time and in the correct thread?

**Comment by brianwyka** [comment]
@ctoestreich I am trying to be reactive on the way out, such that Micronaut treats it as a non-blocking subscription.  I could also take the `@Body` parameter as a `Single` as well.  Not sure what the benefit of that is, however...

**Comment by brianwyka** [comment]
Thinking about it more, seems like it would be non-trivial to have some sort of callback (in reactive style) which executes in the same thread as the polling loop...
