### ISSUE TITLE
Kafka metrics missing tag topic

### ISSUE THREAD

**Issue by ctoestreich** [micronaut-projects/micronaut-kafka#107]
Some of the metrics, like records consumed total, are missing context (tags) like topic.

The metric out of boot looks like this:

<img width="511" alt="Screen Shot 2020-03-13 at 8 25 41 AM" src="https://user-images.githubusercontent.com/691357/76625630-ad99c880-6505-11ea-89a9-a6c4b30ef9ac.png">

The Same metric in Micronaut

<img width="551" alt="Screen Shot 2020-03-13 at 8 37 14 AM" src="https://user-images.githubusercontent.com/691357/76625734-e33eb180-6505-11ea-9882-f4d97abc7b13.png">

**Comment by guillermocalvo** [comment]
Duplicated by: https://github.com/micronaut-projects/micronaut-kafka/issues/227
Fixed by: https://github.com/micronaut-projects/micronaut-kafka/pull/513
