### ISSUE TITLE
OffsetStrategy.SYNC_PER_RECORD commits even with exception

### ISSUE THREAD

**Issue by florian-besser** [micronaut-projects/micronaut-kafka#119]
Micronaut version: 1.3.4

This is related to #39 

In the KafkaConsumerProcessor line 542 you check !failed and only commit if there was no exception thrown (for SYNC and ASYNC).

But in KafkaConsumerProcessor line 528 you commit always (even if an exception was thrown) for SYNC_PER_RECORD and ASYNC_PER_RECORD.

Is this the intended behavior? I would have expected that both SYNC / SYNC_PER_RECORD (and their ASYNC counterparts) will only commit if no exception is thrown.

If my expectation is correct I'll submit a PR.

**Comment by graemerocher** [comment]
@florian-besser PRs welcome

**Comment by florian-besser** [comment]
I can no longer see the issue, I must assume I did something wrong - sorry!
