### ISSUE TITLE
Micronaut kafka crashes a few seconds after boot

### ISSUE THREAD

**Issue by acaligiuri** [micronaut-projects/micronaut-kafka#122]
Hi,
I have a very simple CRUD service that sends messages to kafka over 3 different topics.
At the moment, it does nothing more than that:

The service is deployed on openshift on-premises, where we also have a kafka 2.0.0 deployment using the strimzi.io 0.8.2

A few seconds after boot i see this:

> 15:30:53.326 [pool-2-thread-4] INFO  o.a.k.c.admin.AdminClientConfig - AdminClientConfig values:
>	bootstrap.servers = [streaming-kafka-bootstrap.dxl-event-streaming.svc.cluster.local:9092]
>	client.dns.lookup = default
>	client.id = logging-ms-micronaut-graal
>	connections.max.idle.ms = 300000
>	metadata.max.age.ms = 300000
>	metric.reporters = []
>	metrics.num.samples = 2
>	metrics.recording.level = INFO
>	metrics.sample.window.ms = 30000
>	receive.buffer.bytes = 65536
>	reconnect.backoff.max.ms = 1000
>	reconnect.backoff.ms = 50
>	request.timeout.ms = 120000
>	retries = 5
>	retry.backoff.ms = 100
>	sasl.client.callback.handler.class = null
>	sasl.jaas.config = null
>	sasl.kerberos.kinit.cmd = /usr/bin/kinit
>	sasl.kerberos.min.time.before.relogin = 60000
>	sasl.kerberos.service.name = null
>	sasl.kerberos.ticket.renew.jitter = 0.05
>	sasl.kerberos.ticket.renew.window.factor = 0.8
>	sasl.login.callback.handler.class = null
>	sasl.login.class = null
>	sasl.login.refresh.buffer.seconds = 300
>	sasl.login.refresh.min.period.seconds = 60
>	sasl.login.refresh.window.factor = 0.8
>	sasl.login.refresh.window.jitter = 0.05
>	sasl.mechanism = GSSAPI
>	security.protocol = PLAINTEXT
>	send.buffer.bytes = 131072
>	ssl.cipher.suites = null
>	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
>	ssl.endpoint.identification.algorithm = https
>	ssl.key.password = null
>	ssl.keymanager.algorithm = SunX509
>	ssl.keystore.location = null
>	ssl.keystore.password = null
>	ssl.keystore.type = JKS
>	ssl.protocol = TLS
>	ssl.provider = null
>	ssl.secure.random.implementation = null
>	ssl.trustmanager.algorithm = PKIX
>	ssl.truststore.location = null
>	ssl.truststore.password = null
>	ssl.truststore.type = JKS

after that the container exits.

The source is quite simple and it's compiled as native image using `./docker-build.sh`

one thing i notice is that it seems it's trying to use https although i haven't configured it.

Any idea how to debug this problem?

**Comment by graemerocher** [comment]
Have you tried setting the log level to trace to get more diagnostics information?

**Comment by acaligiuri** [comment]
I Have but that still looked like the only relevant message.

I have used the properties `logger.levels.ROOT=TRACE`, `logger.levels.org.apache: TRACE` and `logger.levels.org.apache.kakfa: TRACE`

anything else i can enable?

**Comment by graemerocher** [comment]
`kakfa` is spelt wrong, try to do this in `logback.xml`. In GraalVM the log levels are initialized at compilation time so you cannot change them at runtime as far as I understand.

**Comment by acaligiuri** [comment]
i will try that thanks

**Comment by ctoestreich** [comment]
Does your application start when running locally against a local kafka server?  These types of issues, we have found, tend to be in routing in OSE (ie, service name bine misconfigured) or security of the cluster we are attaching to when deployed.  Post some logs if you can't figure it out.

**Comment by acaligiuri** [comment]
Hi @ctoestreich thanks for your reply.
This is kind of a pet project for me at work and I've been fully booked with other priorities this week.
I currently have another solution implemented in java with spring-boot 2.0.5, in the same namespace connected to the same kafka cluster and it has no issue with routing or security (network policy is not configured anyways).

As for the logs, i have yet to try @graemerocher solution but i will this weekend. Up until now i see 0 logs.

I do not have a local cluster but as last resort i might try that.

**Comment by acaligiuri** [comment]
Hi @graemerocher 
I put the root logger at TRACE level. I have to say i did not see much regarding the kafka client, but i see a bunch of exceptions i have to investigate coming from netty. (see attached file)
[logging-ms-micronaut-gra-6-26q8r.log](https://github.com/micronaut-projects/micronaut-kafka/files/4562948/logging-ms-micronaut-gra-6-26q8r.log)

I wonder if this has anything to do with my upgrading to micronaut 1.3.0. 

When downgrading to 1.2.11 i see this during native compilation:

> Warning: class initialization of class io.micronaut.configuration.kafka.embedded.KafkaEmbedded failed with exception java.lang.NoClassDefFoundError: org/I0Itec/zkclient/serialize/ZkSerializer. This class will be initialized at run time because option --allow-incomplete-classpath is used for image building. Use the option --initialize-at-run-time=io.micronaut.configuration.kafka.embedded.KafkaEmbedded to explicitly request delayed initialization of this class.

**Comment by graemerocher** [comment]
Cannot reproduce this myself, if you come up with an example application we can look at we can take another look
