### ISSUE TITLE
Feature Request: Add enable parameter for Kafka configuration

### ISSUE THREAD

**Issue by marcosflobo** [micronaut-projects/micronaut-kafka#138]
I'd like to propose a feature request about the Kafka configuration in micronaut.

The idea is to create a missing parameter to disable/enable the whole Kafka configuration. See an example at the end.

### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. If the parameter is set to`false`, the Kafka configuraiton will not be taken into consideration
2. If the parameter is set to `true`, the Kafka configuration will be taken into consideration
3. If the parameter is not set, the behavior would be the same than if the parameter is set to `true`

### Expected Behaviour

- If the parameter is set to`false`, the Kafka configuraiton will not be taken into consideration
- If the parameter is set to `true`, the Kafka configuration will be taken into consideration
- If the parameter is not set, the behavior would be the same than if the parameter is set to `true`

### Actual Behaviour

This parameter does no exists today https://micronaut-projects.github.io/micronaut-kafka/latest/guide/configurationreference.html

### Environment Information

- **Operating System**: all
- **Micronaut Version:** all
- **JDK Version:** all

### Example Application

```
...
kafka:
  enable: false
  bootstrap:
    servers: localhost:9092
...
```
The proposed parameter is named `enable` in this example.

#### Use case
- A microservice consumes from Kafka
- At some point, this microservice evolves and should be able to work with both Kafka or another messaging system
- The Kafka could be present or not
- We need to disable the Kafka config if the microservice is deployed in an environment where the Kafka is not present and avoid crashes when the microservice runs

**Comment by graemerocher** [comment]
Thanks for the contribution!
