### ISSUE TITLE
Why does the processor loop commit the offset at shutdown?

### ISSUE THREAD

**Issue by hnybom** [micronaut-projects/micronaut-kafka#14]
https://github.com/micronaut-projects/micronaut-kafka/blob/32e235818d1af72ad7e60b1e9ae793a4bfefe749/kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java#L487

Why is the offset committed at shutdown even if offset strategy is disabled? E.g. if there is a bug in the consumer code and you want to fix it and then resume message processing you will miss out all of the messages that where not successfully acked

**Comment by graemerocher** [comment]
This looks like a bug, thanks for the report
