### ISSUE TITLE
Optional health check for cluster

### ISSUE THREAD

**Issue by ctoestreich** [micronaut-projects/micronaut-kafka#15]
Our access to kafka via ssl is limited to topics and not to the cluster and the admin client can't access the cluster and constantly throws the following excetion

```bash

2019-03-05 11:31:54.326 CST ERROR   - [pool-1-thread-1] Health indicator [kafka] reported exception: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.
```

I will add a feature to optionally disable this health check.  Something like this perhaps?

```java
@Requires(property = AbstractKafkaConfiguration.PREFIX + ".health.enabled", value = "true", defaultValue = "true")
```

**Comment by graemerocher** [comment]
Seems reasonable PR welcome

**Comment by infinityat0** [comment]
This probably isn't sufficient because `ConsumerConfig` in kafka-client jar will now look at `kafka.health.enabled` flag and call it UNKNOWN. Throws a pesky warning message. 

```
The configuration 'health.enabled' was supplied but isn't a known config.
```

**Comment by timurstrekalov** [comment]
This probably should've been put under `HealthEndpoint.PREFIX + ".kafka.enabled"` rather than `AbstractKafkaConfiguration.PREFIX + ".health.enabled"`, to both make it consistent and avoid the warning message above?
