### ISSUE TITLE
KAFKA_BOOTSTRAP_SERVERS env variable is being ignored

### ISSUE THREAD

**Issue by brandon-johnson-globality** [micronaut-projects/micronaut-kafka#179]
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Create an application that uses Micronaut Kafka
2. Set kafka.bootstrap.servers via application.yml
3. Set KAFKA_BOOTSTRAP_SERVERS environment variable
4. Inject KafkaDefaultConfiguration into test
5. Assert that KafkaDefaultConfiguration.getConfig().getProperty("bootstrap.servers") is equal to value set via environment variable.

### Expected Behaviour

KAFKA_BOOTSTRAP_SERVERS env variable should override the value set via kafka.bootstrap.servers in application.yaml

### Actual Behaviour

The value of KAFKA_BOOTSTRAP_SERVERS is ignored.

### Test Stack Trace

`org.opentest4j.AssertionFailedError: expected: <setbyenv:1234> but was: <setbyappyaml:1234>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
	at bootstrap.servers.example.BootstrapServersExampleTest.testThatBootstrapServersAreSetViaEnvironmentVariable(BootstrapServersExampleTest.java:25)`

### Environment Information

- **Operating System**: OSX
- **Micronaut Version:** 2.0.0
- **Micronaut Kafka Version:** 2.0.0
- **JDK Version:** 8,11,13

### Example Application

https://github.com/brandon-johnson-globality/micronaut-kafka-bootstrap-servers

**Comment by WojciechLuczkow** [comment]
For now it works correctly if using environment properties like:
```yaml
kafka.bootstrap.servers
kafka.other.property
```
instead

**Comment by beedub** [comment]
@WojciechLuczkow can you elaborate on your comment above? Trying to figure out how to workaround this as well

**Comment by WojciechLuczkow** [comment]
> @WojciechLuczkow can you elaborate on your comment above? Trying to figure out how to workaround this as well

Literally name your Env property like properties in Kafka.
i.e. `export kafka.bootstrap.servers=localhost:9092`
