### ISSUE TITLE
Allow pausing and resuming Kafka consumers

### ISSUE THREAD

**Issue by dcmoeller** [micronaut-projects/micronaut-kafka#19]
Hello,

I've posted a question on StackOverflow describing the task I want to implement:

[How to implement HTTP endpoint in Micronaut to pause consumption of messages from Kafka?](https://stackoverflow.com/questions/54927782/how-to-implement-http-endpoint-in-micronaut-to-pause-consumption-of-messages-fro)

To me it comes down to the correct way to interact with instances of KafkaConsumer like pausing/resuming or changing subscriptions.
I've implemented a HTTP Controller (see below) to react to (what I would call) management requests to e.g. change subscriptions (in effect removing/adding a subscription to a specific Kafka Topic).
This Controller also implements io.micronaut.configuration.kafka.KafkaConsumerAware to get a reference to the active KafkaConsumer instance to change it's subscriptions.
But invocation of pause(...), resume(...), or subscribe(...) yields java.util.ConcurrentModificationException all the time, making interface KafkaConsumerAware useless (as far as I can see).

Am I missing something?

Christian

### Task List

- Run the application, then issuing
`$ curl -X PUT http://localhost:8080/operation/suspend`
yields:
`{"message":"Internal Server Error: KafkaConsumer is not safe for multi-threaded access"}`

- Stacktrace on console:
```
2019-03-04T12:38:05.224+01 [pool-1-thread-14] INFO  - Requested to SUSPEND operation! Unsubscribing [org.apache.kafka.clients.consumer.KafkaConsumer@4a3bd45b]
2019-03-04T12:38:05.228+01 [pool-1-thread-14] ERROR - Unexpected error occurred: KafkaConsumer is not safe for multi-threaded access
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
   at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:2201)
   at org.apache.kafka.clients.consumer.KafkaConsumer.acquireAndEnsureOpen(KafkaConsumer.java:2185)
   at org.apache.kafka.clients.consumer.KafkaConsumer.unsubscribe(KafkaConsumer.java:1025)
   [...]
```

### Environment Information

- **Operating System**: Ubuntu
- **Micronaut Version:** 1.0.4
- **JDK Version:** OpenJDK 11.0.1

### Example Application
```java
import io.micronaut.configuration.kafka.ConsumerAware;
import io.micronaut.configuration.kafka.annotation.KafkaListener;
import io.micronaut.configuration.kafka.annotation.Topic;
import io.micronaut.http.HttpResponse;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.micronaut.http.annotation.Put;
import org.apache.commons.lang3.Validate;
import org.apache.kafka.clients.consumer.Consumer;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Nonnull;
import javax.annotation.concurrent.GuardedBy;
import javax.annotation.concurrent.ThreadSafe;
import javax.inject.Singleton;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.Set;

import static io.micronaut.configuration.kafka.annotation.OffsetStrategy.DISABLED;
import static io.micronaut.http.HttpResponse.ok;
import static io.micronaut.http.MediaType.APPLICATION_JSON;
import static java.util.Set.of;

@ThreadSafe
@Singleton
@Controller("/operation")
public final class BusinessController implements ConsumerAware {

  private static final Logger LOG = LoggerFactory.getLogger(BusinessController.class);
  private static final String BUSINESS_TOPIC = "business";

  @GuardedBy("kafkaConsumers")
  private final Set<Consumer> kafkaConsumers = new HashSet<>();
  @GuardedBy("kafkaConsumers")
  private boolean suspended = false;

  @KafkaListener(groupId = "business-${micronaut.environments:default}",
          offsetStrategy = DISABLED)
  @Topic(BUSINESS_TOPIC)
  public void receiveRecord(@Nonnull final ConsumerRecord<String, String> record,
                            @Nonnull final Acknowledgement acknowledgement) {
    // Business operation with received Kafka message.
  }

  @Override
  public void setKafkaConsumer(@Nonnull final Consumer consumer) {
    Validate.notNull(consumer, "Missing Kafka Consumer instance");
    LOG.info("Got aware of a Kafka Consumer {} with subscriptions to {}", consumer, consumer.subscription());
    synchronized (kafkaConsumers) {
      this.kafkaConsumers.add(consumer);
    }
  }

  @Put(uri = "/suspend", produces = APPLICATION_JSON)
  public HttpResponse<String> suspendOperation() {
    final Collection<Consumer> copyOfConsumers;
    synchronized (kafkaConsumers) {
      this.suspended = true;
      copyOfConsumers = new ArrayList<>(kafkaConsumers);
    }
    LOG.info("Requested to SUSPEND operation! Unsubscribing {}", copyOfConsumers);
    copyOfConsumers.forEach(consumer -> {
      synchronized (consumer) {
        consumer.unsubscribe();
      }
    });
    return status();
  }

  @Put(uri = "/resume", produces = APPLICATION_JSON)
  public HttpResponse<String> resumeOperation() {
    final Set<String> topicsToSubscribeTo = of(BUSINESS_TOPIC);
    final Collection<Consumer> copyOfConsumers;
    synchronized (kafkaConsumers) {
      this.suspended = false;
      copyOfConsumers = new ArrayList<>(kafkaConsumers);
    }
    LOG.info("Requested to RESUME operation! Subscribing {} to topic '{}'", copyOfConsumers, BUSINESS_TOPIC);
    copyOfConsumers.forEach(consumer -> {
      synchronized (consumer) {
        consumer.subscribe(topicsToSubscribeTo);
      }
    });
    return status();
  }

  @Get(produces = APPLICATION_JSON)
  public HttpResponse<String> status() {
    final String currentStatus;
    synchronized (kafkaConsumers) {
      currentStatus = suspended ? "SUSPENDED" : "ACTIVE";
    }
    return ok("{\"status\":\"" + currentStatus + "\"}");
  }

}
```

**Comment by ctoestreich** [comment]
I see in spring cloud streams they don't explicitly provide this feature in the framework and rely on examples in docs in both spring-kafka and streams to illustrate how to do this.

https://cloud.spring.io/spring-cloud-static/spring-cloud-stream-binder-kafka/2.1.0.RC3/single/spring-cloud-stream-binder-kafka.html#pause-resume

https://docs.spring.io/spring-kafka/docs/current/reference/#pause-resume

@dcmoeller Are you advocating for this function to be available in the core framework?  It seems there is some tight coupling in your example to having to know about the topic specifically in your operations.  Ultimately the functionality above would be best served at a named consumer level to manage running state individually.

This feature may have come in handy a few times for us in the past few months where our streams die and being able to "start" them again would be great, but I am not sure if a dead consumer can be started via the above or not.

**Comment by graemerocher** [comment]
I think to make this work we would need an API that has `pause()`, `unpause()`, `subscribe` `unsubscribe()` operations that interact with the while loop in https://github.com/micronaut-projects/micronaut-kafka/blob/master/kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java

The methods would have to set some atomic boolean flags or maybe an enum with an `AtomicReference` and the while loop would have to pause the consumer and then watch until the state is changed back

As the message says you cannot interact with the consumer outside of the poll() loop thread so to support this we would need to add a new API

**Comment by dcmoeller** [comment]
@ctoestreich 
> I see in spring cloud streams they don't explicitly provide this feature in the framework and rely on examples in docs in both spring-kafka and streams to illustrate how to do this.
> [...]
> 
> https://docs.spring.io/spring-kafka/docs/current/reference/#pause-resume

If you follow this down to chapter [Listener error handlers](https://docs.spring.io/spring-kafka/docs/current/reference/#listener-error-handlers) you will find the following statement with sample code:

> If your error handler implements this interface, you can, for example, adjust the offsets accordingly. For example, to reset the offset to replay the failed message, you could do something like the following:

To me this sounds quite promising :-)

> @dcmoeller Are you advocating for this function to be available in the core framework? It seems there is some tight coupling in your example to having to know about the topic specifically in your operations. Ultimately the functionality above would be best served at a named consumer level to manage running state individually.

Indeed, my example code shows tight coupling, I would like to decouple Kafka message controllers from HTTP ones later on, but I hope you get the point I want to describe.

**Comment by dcmoeller** [comment]
Your Micronaut Kafka documentation shows example code who implements `KafkaConsumerAware` interface (in [Chapter 5.3 Commiting Kafka Offsets](https://micronaut-projects.github.io/micronaut-kafka/latest/guide/#kafkaOffsets)). This "inspires" me to my solution: Here you're getting a reference to the underlying KafkaConsumer instance to manage all this kind of Topic Subscription etc.
But in the end implementing it does not help with this goal (as described above with the `java.util.ConcurrentModificationException` stuff).
To me this example along with the interface type's name is misleading, it's unclear how to use it correctly. Maybe it only works correctly when dealing in conjunction with interface `ConsumerRebalanceListener` (as in the example code "Manually Assigning Offsets to a Consumer Bean")? So maybe rename it? Or change it's implemenation accordingly?

**Comment by graemerocher** [comment]
There is nothing misleading about the documentation, you can indeed get a reference to the consumer and commit offsets manually and this works totally fine when this is done within the listener method that runs inside the Kafka `poll` loop.

What you cannot do and what Kafka doesn't allow you to do is access that consumer from a thread other than the `poll` loop which is what you are attempting to do. If you wish to clarify the documentation on this front please go ahead.

What we lack is the equivalent of the `KafkaListenerEndpointRegistry` as referenced in Spring Kafka which provides an API pausing and resuming listeners

**Comment by dcmoeller** [comment]
@graemerocher 
> There is nothing misleading about the documentation, you can indeed get a reference to the consumer and commit offsets manually and this works totally fine when this is done within the listener method that runs inside the Kafka poll loop.

This scenario is supported by adding the `KafkaConsumer` as additional parameter to any kind of method receiving messages from Kafka (the ones annotated with `@Topic`).

> What you cannot do and what Kafka doesn't allow you to do is access that consumer from a thread other than the poll loop which is what you are attempting to do. If you wish to clarify the documentation on this front please go ahead.

This pattern of usage is suggested by implementing `KafkaConsumerAware`: To be able to manipulate `KafkaConsumer` instances regardless of any threading/Kafka poll()-loop issues. And that's what I want to express with "misleads me".

**Comment by graemerocher** [comment]
Where is suggested? If you believe that it is suggested somewhere feel free to improve the docs that suggest that

**Comment by graemerocher** [comment]
After this commit you can use the `ConsumerRegistry` interface to pause and resume consumers.
