### ISSUE TITLE
Tracing span not automatically started/continued by KafkaListener

### ISSUE THREAD

**Issue by mattlong-finocomp** [micronaut-projects/micronaut-kafka#206]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. run docker-compose up -d
2. run mn-kafka-tracing
3. navigate to localhost:9411 and search traces

### Expected Behaviour

The Kafka Listener should start a span, add the traceId and spanId to the MDC and they should appear in the SLF4j log messages.
If the consumed Kafka message was sent with the tracing ID(s) then the new span should be a child of the sent message.

### Actual Behaviour

A KafkaClient automatically creates a span when sending a message, but the KafkaListener does not.

### Environment Information

- **Operating System**: Pop!_OS 20.04
- **Micronaut Version:** 2.0.1
- **JDK Version:** zulu openjdk 11.0.7

### Example Application

https://github.com/mattlong-finocomp/mn-kafka-tracing

**Comment by graemerocher** [comment]
Please provide an example. Thanks

**Comment by mattlong-finocomp** [comment]
@graemerocher I've created a sample applicaiton and edited the original comment.

**Comment by StephanePaulus** [comment]
Hello @mattlong-finocomp I also stumbled on this issue, did you find a workaround? I tried adding this, but with no luck.
```
    @Topic("mine")
    public void receive(ConsumerRecord<String, String> record) {
        BraveTracer tracer = applicationContext.getBean(BraveTracer.class);
        SpanContext spanContext = TracingKafkaUtils.extractSpanContext(record.headers(),tracer);
        log.info("Received message: {} {}", record.key(), record.value());
        tracer.buildSpan("kafkaReceive").asChildOf(spanContext).start()
    }
```

**Comment by mattlong-finocomp** [comment]
No I never found a workaround

**Comment by StephanePaulus** [comment]
@mattlong-finocomp  I don't know if you are interested, but today I made some progress on a workaround.

```
    @Inject
    Tracing tracing;
  
    @Topic("mine")
    public void receive(ConsumerRecord<String, String> record) {
        BraveTracer tracer = BraveTracer.create(tracing);
        SpanContext spanContext =  TracingKafkaUtils.extractSpanContext(record.headers(),tracer);
        final BraveSpan braveSpan = tracer.buildSpan("span0").asChildOf(spanContext).start();
        tracer.activateSpan(braveSpan);
        //Other methods, in my case span 1, span 2, .., with the Micronaut annotation `@NewSpan`
        braveSpan.finish();
```
<img width="1614" alt="Screenshot 2021-01-20 at 22 35 25" src="https://user-images.githubusercontent.com/37271518/105243852-ecf66400-5b6f-11eb-810a-1c8be80a7c0f.png">

**Comment by abhikumarblume** [comment]
I am also facing the same issue as mentioned in this bug.
@graemerocher  Can we please expedite bug fixing of this issue ?

**Comment by graemerocher** [comment]
You can always annotate the listener method with @NewSpan seems like a nice have but PRs are welcome!
