### ISSUE TITLE
'latest' documentation is not the latest one but the future one

### ISSUE THREAD

**Issue by loicmathieu** [micronaut-projects/micronaut-kafka#25]
The 'by default' documentation of micronaut kafka that is accessible here https://micronaut-projects.github.io/micronaut-kafka/latest/guide/ is the documentation for the future version (1.0.0.RC2 at the time of writing this issue) and not the current one (1.0.4 at the time of writing).

This is not coherent with the 'latest' documentation of micronaut core that is the correct one.

This leads to misunderstanding issue for developers that show features that are not yet available with the current version (like disactivating the kafka endpoint).

Regards,

Loïc

**Comment by graemerocher** [comment]
1.0.x is available at  https://micronaut-projects.github.io/micronaut-kafka/1.0.x/guide

**Comment by loicmathieu** [comment]
Yes, that's my point, github README and the links from the core micronaut links to the latest version that are the futur one so they shoud links to https://micronaut-projects.github.io/micronaut-kafka/1.0.x/guide or the latest should link to the 1.0.4.

It's really error prone that the documentation you find by clicking on guthub or micronaut core documentation is not the current one but the future one (I lost a few hours wondering why I cannot disabled the kafka healthcheck ...)

**Comment by demis27** [comment]
It's not already done? For me https://micronaut-projects.github.io/micronaut-kafka/latest/guide/ is the documenttion of V1.3.0 (last release) @loicmathieu can you confirm this?

**Comment by graemerocher** [comment]
Old issue, closing
