### ISSUE TITLE
kafka.bootstrap.servers can't handle YAML list

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-kafka#26]
The documentation states that you can specify a list of Kafka servers with `kafka.bootstrap.servers`.

https://micronaut-projects.github.io/micronaut-kafka/latest/guide/index.html#kafkaQuickStart

But doing so results in an error. The list is converted to a string but Kafka expects a list.

A workaround is to specify a commma separated string like this:
```
kafka:
    bootstrap:
        servers: kafka1:9092, kafka2:9092, kafka3:9092
```
### Steps to Reproduce

Create a micronaut application and add Kafka dependency.

`compile 'io.micronaut.configuration:micronaut-kafka'`

Then add a list of servers (one list entry is enough) to applicationn.yml.

```
kafka:
    bootstrap:
        servers:
            - localhost:9092
```

Try to start the application.

`./gradlew run`

### Expected Behaviour

The application should start and try to connect to a Kafka broker on localhost.

### Actual Behaviour

```
Caused by: org.apache.kafka.common.config.ConfigException: Invalid url in bootstrap.servers: [localhost:9092]
        at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:56)
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:712)
        ... 26 common frames omitted
```

The logging output shows the invalid config string:
```
INFO  o.a.k.c.consumer.ConsumerConfig - ConsumerConfig values: 
        auto.commit.interval.ms = 5000
        auto.offset.reset = latest
        bootstrap.servers = [[localhost:9092]]
```

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 1.1.0.M2
- **JDK Version:** 1.8.0_162

### Example Application

https://github.com/goeh/micronaut-kafka-issue-26

**Comment by graemerocher** [comment]
probably a comma separated list would work

**Comment by zthulj** [comment]
This problem will happen for all the *list* fields of the kafka clients. (Kafka client is waiting a coma separated value, and convert it to an array)

To resolve this, I suggest that we create an "ArraytoStringConverter" class, and automatically call it for each config read in KafkaDefaultConfiguration.resolveDefaultConfiguration.

I can work on it.

**Comment by graemerocher** [comment]
Yes what is missing is the `ArrayToStringConverter` and possibly `ListToStringConverter`
