### ISSUE TITLE
[WishList item] Kotlin coroutines/flow support

### ISSUE THREAD

**Issue by nkiesel** [micronaut-projects/micronaut-kafka#282]
Hi,

are there any plans to explicitly support Kotlin, especially by using coroutines and Kotlin Flow objects?

**Comment by sskrla** [comment]
Note that where ever you can inject `Flowable`, you should also be able to inject Kotlin's `Flow` as Micronaut will automatically convert them as of [this PR](https://github.com/micronaut-projects/micronaut-core/pull/2539/)
