### ISSUE TITLE
Micronaut-Kafka with auto.commit.enable=false: how commit manually an offset?

### ISSUE THREAD

**Issue by jimisdrpc** [micronaut-projects/micronaut-kafka#298]
Straigth question: how commit manually an offset after processed it instead of relying on consumer.commitSync() been called behind the scene?

my consumer

`package com.tolearn.consumer

import io.micronaut.configuration.kafka.annotation.KafkaKey
import io.micronaut.configuration.kafka.annotation.KafkaListener
import io.micronaut.configuration.kafka.annotation.OffsetStrategy
import io.micronaut.configuration.kafka.annotation.Topic
import io.micronaut.messaging.annotation.Header

@KafkaListener(groupId="myGroup",offsetStrategy=OffsetStrategy.SYNC_PER_RECORD)
class DemoConsumer {
    @Topic("demotopic")
    fun receive(@KafkaKey key: String?,
                msg: String,
                offset: Long,
                partition: Int,
                topic: String,
                timestamp: Long,
                header: Header
    ){
        println("Key = $key " +
                "msg = $msg " +
                "offset = $offset " +
                "partition = $partition " +
                "topic = $topic " +
                "timestamp = $timestamp " +
                "header = $header"
        )

        //saved to database

        // how commit like consumer.commitOffsets(true)
        //Consumer.commitSync()
    }
}`

application.yml

micronaut:
  application:
    name: demoGrpcKafka
  executors:
    consumer:
      type: fixed
      nThreads: 1
#kafka.bootstrap.servers: localhost:9092
kafka:
  bootstrap:
    servers: localhost:9092
  consumers:
    default:
      auto:
        commit:
          enable: false
  producers:
    #default:
    demo-producer:
      retries: 2

PS.: similar question originally posted in https://stackoverflow.com/questions/65246599/micronaut-kafka-with-auto-commit-enable-false-how-commit-manually-an-offset

**Comment by graemerocher** [comment]
See docs https://micronaut-projects.github.io/micronaut-kafka/latest/guide/index.html#kafkaOffsets under "Manually Committing Offsets"
