### ISSUE TITLE
KafkaClient not producing keys despite using @KafkaKey annotation

### ISSUE THREAD

**Issue by codependent** [micronaut-projects/micronaut-kafka#30]
I'm using Micronaut 1.1.0 and Kafka 2.2.0.

This is my KafkaProducer:
```
@KafkaClient
interface CustomerKafkaProducer {

    @Topic("customer")
    fun sendCustomer(@KafkaKey id: Int, customer: Customer)

}
```
Despite passing a non null id as the KafkaKey the message is published without a key in the customer topic as I can see using the kafka-console-consumer:
``` 
/opt/confluent-5.2.1/bin/kafka-console-consumer --topic customer --from-beginning --bootstrap-server localhost:9092 --property print.key=true
	{"id":3,"name":"John","address":"Cipress Street"}
	{"id":4,"name":"John","address":"Cipress Street"}
```
If I create a message with kafka-console-producer these messages do have a key as expected:
```
/opt/confluent-5.2.1/bin/kafka-console-producer --topic customer --broker-list localhost:9092 --property "parse.key=true" --property "key.separator=:"
>6:myvalue
```
Now reading again:
```
/opt/confluent-5.2.1/bin/kafka-console-consumer --topic customer --from-beginning --bootstrap-server localhost:9092 --property print.key=true
	{"id":3,"name":"John","address":"Cipress Street"}
	{"id":4,"name":"John","address":"Cipress Street"}
6	myvalue
```

Is this a bug or there's some other way of specifying the message key?

**Comment by graemerocher** [comment]
Not that I am aware of, will try reproduce but we have plenty of tests that use `@KafkaKey`

**Comment by codependent** [comment]
Sorry for the unnecessary issue, the key is being correctly set. I was misled because in Confluent's Control Center the topic messages showed and empty key, and then I checked with the kafka-console-consumer script and apparently it wasn't there either. However it is there I just needed to add the proper key deserializer:

```
/opt/apache/kafka_2.12-2.1.1/bin/kafka-console-consumer.sh --topic customer --from-beginning --bootstrap-server localhost:9092 --property print.key=true --key-deserializer org.apache.kafka.common.serialization.IntegerDeserializer
5	{"id":5,"name":"John","address":"Cipress Street"}
```
