### ISSUE TITLE
Add documentation on ReadOnlyKeyValueStore

### ISSUE THREAD

**Issue by kamilgregorczyk** [micronaut-projects/micronaut-kafka#36]
Please add some tutorial/documentation on how a KTable can be transformed to ReadOnlyKeyValueStrore and how values can be retrieved (form the same node and from other ones)

**Comment by guillermocalvo** [comment]
You can find an example of how to use `ReadOnlyKeyValueStore` in the ["Interactive Query Service" section of the Micronaut Kafka  Guide](https://micronaut-projects.github.io/micronaut-kafka/latest/guide/#kafkaStreamInteractiveQuery).
