### ISSUE TITLE
Prevent paused Kafka Listeners from processing unacked messages at application startup.

### ISSUE THREAD

**Issue by RajRohil** [micronaut-projects/micronaut-kafka#374]
I am using Kafka listeners (@KafkaListener) in my application. 

I want to keep the consumers in paused state during the application startup and enable the consumers on demand after the application has started up. I am using ConsumerRegistry to achieve this. It works fine where there is no lag in the consumer groups.

The issue occurs when there are unacked messages. The Listener processes all the unacked messages even though  the consumers have already been paused.

### STEPS TO REPRODUCE:

1. Create a Kafka Listener.
2. Create a Modifier which pauses the consumer before application startup. Have tried to trigger this with multiple ServerStartEvent, PostConstruct of the KafkaListeners, ConsumerRegistry bean creation event. None gave the desired behaviour.
3. Reset offset of the kafka consumer.
4. Start the micronaut application.

### OUTCOME
I observed that the consumers are paused correctly, still the control transfers to the KafkaListener and the message consumption happens.

Is there any way to prevent this? Can we have a way to build a KafkaListener in paused state? Or is there any application event/hook on which the consumers can be paused to prevent this behaviour?

Something like this can help: https://docs.spring.io/spring-kafka/api/org/springframework/kafka/annotation/KafkaListener.html#autoStartup()

MICRONAUT VERSION : 2.2.2
MICRONAUT KAFKA VERSION: 3.1.0
KAFKA VERSION: 2.6.0

**Comment by graemerocher** [comment]
Looks like we don't have a way to prevent auto start and that would need to be added as a separate API to the `ConsumerRegistry` interface

**Comment by RajRohil** [comment]
@graemerocher This will be part of which milestone?

In the meantime I was trying to pause the consumers using ConsumerRegistry at the startup event. This works intermittently. It depends on when the Kafka consumers are getting assigned and joining the cluster. It works fine when the consumer registration is completed before the startup event is triggered. On the contrary when registration is not completed before the startup event and the consumer pause api is triggered, then the ConsumerRegistry updates the consumer as paused but in actual the consumers are not paused.

Since the consumer registration is happening in a separate thread pool, it is difficult to figure out when to actually pause the consumers. 

In the existing implementation is there any application event which can be consumed to determine if the consumer registration process has been completed?

**Comment by graemerocher** [comment]
It is not scheduled to any milestone yet but contributions are of course welcome

**Comment by dstepanov** [comment]
Introduced autoStartup option for this case https://github.com/micronaut-projects/micronaut-kafka/pull/442
