### ISSUE TITLE
Release a new version compatible with Micronaut 3.0

### ISSUE THREAD

**Issue by ilopmar** [micronaut-projects/micronaut-kafka#384]
Please follow the instructions in https://github.com/micronaut-projects/micronaut-core/issues/5607 and update that core issue with the information related to the upgrade.

**Comment by graemerocher** [comment]
See https://github.com/micronaut-projects/micronaut-kafka/pull/385

**Comment by graemerocher** [comment]
4.0.0.RC1 is compatible with Micronaut 3.0
