### ISSUE TITLE
Number of partition for topic in embedded kafka is hardcoded to 1 

### ISSUE THREAD

**Issue by kziomek** [micronaut-projects/micronaut-kafka#41]
I aimed to implement test with embedded kafka with topic having 10 log partitions.
I pass `num.partitions` param to broker properties in `application-test.yml`

```
kafka:
  embedded:
    enabled: true
    topics: my-topic
    properties:
      num.partitions: 10
  ```

With configuration above I received topic with 1 partition only so I looked deeper into KafkaEmbedded.java 
I can see `num.partitions` is passed all the way to KafkaConfig constructor. So good so far.

And then value is ignored when topic is created around line 147 in KafkaEmbedded.java
(exact line depend on micronaut-kafka version, but current master branch still hardcode it to 1)

```
adminClient.createTopics(topics.stream().map(s -> new NewTopic(s, 1, (short) 1)).collect(Collectors.toList()))
                               .all().get();
```

 Is there any reason I don't know about that number of partitions is hardcoded to 1?

 Otherewise would be nice to have option to create topics with many partitions for better confidence in tests.

**Comment by kziomek** [comment]
I've created Pull Request with one way of implementing it so you can see what I mean.
[https://github.com/micronaut-projects/micronaut-kafka/pull/42](Pull Request)

I can see test "test send valid UUID key" failed in Travis. I'm not sure why as all tests are passing on my machine with Java 8 and I cannot reproduce it. 

What are your thoughts ?

**Comment by graemerocher** [comment]
Thanks for the contribution!
