### ISSUE TITLE
Support of TopologyTestDriver for Micronaut test

### ISSUE THREAD

**Issue by victorbonnet** [micronaut-projects/micronaut-kafka#417]
### Feature description

Hello, 

We have noticed that using GlobalKTable in our Topology would break our test that would end up with a timeout exception. 
[Here is a simple project ](https://github.com/victorbonnet/dummy-kafka-streams/blob/master/src/main/java/dummy/kafka/streams/ExampleFactory.java#L24-L35)where we can reproduce the problem.

Thanks to [Matthias J. Sax](https://twitter.com/MatthiasJSax/status/1441670822385442818) we have noticed that it's due to a [missing integration of Micronaut and TTD](https://twitter.com/MatthiasJSax/status/1441670822385442818).

> The timeout does not come from TTD but from the unnecessarily created KafkaStreams client that tries to connect to a non-existing broker and eventually fails with a timeout. If there is no global table there is not timeout (due to different internal behavior of KafkaStreams).

I believe we can already mock the bean that initializes TTD, but It's not necessarily trivial and it's hard to know for the devs that using TTD implies doing such changes. 

Thanks

**Comment by graemerocher** [comment]
PRs welcome in this area

**Comment by victorbonnet** [comment]
Closing the issue as it was fixed in this PR: https://github.com/micronaut-projects/micronaut-kafka/pull/555

Thanks @Usy!
