### ISSUE TITLE
Support for setting uncaught exception handler

### ISSUE THREAD

**Issue by pqab** [micronaut-projects/micronaut-kafka#424]
### Feature description

There is a new handler `StreamsUncaughtExceptionHandler` added in Kafka 2.8.0

We would like to use `REPLACE_THREAD` instead of the default value `SHUTDOWN_CLIENT` when there is exception throw, but the handler needs to be added before the Kafka Stream started.

It would be nice if we can set a custom handler for it

**Comment by sumant-turlapati** [comment]
I will second this.

**Comment by graemerocher** [comment]
not tried it personally, did it work for you?

**Comment by sumant-turlapati** [comment]
Yes this worked for me.

**Comment by pqab** [comment]
thanks, I tried the workaround, it worked
