### ISSUE TITLE
Make Kafka healthcheck configurable for apps that doesn't create topics

### ISSUE THREAD

**Issue by artfable** [micronaut-projects/micronaut-kafka#440]
### Feature description

Currently healthcheck is done only based on `offsets.topic.replication.factor` kafka property, that cause status DOWN when kafka has less brokers than replication factor. It makes sense only for applications that managing topic creation. For applications that only read/write to the existing topics `min.insync.replica` should be taken into an account.

Would be nice to have a possibility to configure behaviour of the healthcheck.

**Comment by jonasgeiregat** [comment]
I follow @artfable's  concern that `offsets.topic.replication.factor` is far from an ideal property to monitor the health.

But I'm not sure about the clusters `min.insync.replicas` setting either as this can be overridden on a per topic basis. This can cause the health check to succeed while you're unable to produce messages on a topic with a higher `min.insync.replicas` setting then globally defined on a cluster level.

Next to that `min.insync.replicas` is only useful from a producing point of view but what if your application only consumes ?

**Comment by guillermocalvo** [comment]
Closed by #774 and #810
