### ISSUE TITLE
Publish events before/after consumer start for regular kafka consumers

### ISSUE THREAD

**Issue by racevedoo** [micronaut-projects/micronaut-kafka#457]
### Feature description

Publishing events before and after consumer start is useful for the application to "prepare itself" for receiving records (like loading in-memory caches, for example).

I noticed that there are events for kafka streams (`AfterKafkaStreamsStart` and `BeforeKafkaStreamStart`), so I guess we can add this for regular kafka consumers too.

**Comment by gigilee** [comment]
Looking forward to this feature support.
