### ISSUE TITLE
Missing the ConsumerSeekAware interface

### ISSUE THREAD

**Issue by manuel-domke** [micronaut-projects/micronaut-kafka#46]
Hello,

I'm having trouble using "seek()" in a meaningful way:
In our case, it is required for all messages to be processed in the correct order, so we do a seek to the last processed offfset if an exception occured. 

Unfortunately, the KafkaListener simply ignores the seek position it and just continues where it was, then realizing there is a previous offsets that has to be processed first, doing the seek again and never getting out of this loop. 
Using OffsetReset.EARLIEST and OffsetStrategy.DISABLED options for the Listener and doing sync commits for all messages that have been processed successfully.

After some search, I found out that the Spring framework has the ConsumerSeekAware for exactly this purpose.

What are the chances something like this will/can be integrated to Micronaut? I'd be happy to contribute some code if this feature is anticipated at all.

**Comment by graemerocher** [comment]
There was a recent change in master to handle exceptions and seek to last position. See https://github.com/micronaut-projects/micronaut-kafka/blob/master/kafka/src/test/groovy/io/micronaut/configuration/kafka/errors/KafkaErrorHandlingSpec.groovy#L57

Does that not serve your purpose?

**Comment by manuel-domke** [comment]
Indeed I was thinking about just throwing an exception after calling seek(), so it restarts the poll loop and starts from where I want to. Thanks for this hint!

But after reading though #39, I figured out it may be much simpler to simply do the retry (a limited number of consecutive retries per message) immedietaly in the receive function instead of utiliziling kafka for this.
