### ISSUE TITLE
Upgrade Kafka to 3.0.0

### ISSUE THREAD

**Issue by benkeil** [micronaut-projects/micronaut-kafka#474]
In order to run Kafka Streams on a Mac M1 you need a the newest (not yet released) version of RocksDB, which is incompatible with the implementation in kafka-streams 2.8.0.

**Comment by victorbonnet** [comment]
in addition ARM support, the `2.8.0` release of kafka-streams contains [vulnerabilities](https://mvnrepository.com/artifact/org.apache.kafka/kafka-streams/2.8.0) which are not fixed in the other `2.8.X` releases.

**Comment by graemerocher** [comment]
fixed by https://github.com/micronaut-projects/micronaut-kafka/commit/229bd9b3c1b6c73bc5739440b1fe4ebcac90a4f4
