### ISSUE TITLE
Support multi-cluster kafka consumer / publisher

### ISSUE THREAD

**Issue by yli-brex** [micronaut-projects/micronaut-kafka#482]
### Feature description

Hey,

I think today micronaut kafka only support operation on single kafka cluster set in application.yml / application property. Wish if it's possible, could we allowed consumer / producer specify their own broker endpoint?

**Comment by KaustubhKhati** [comment]
Is this what you are looking for? https://stackoverflow.com/questions/59326261/micronaut-kafka-project-mutiple-consumers-each-with-different-bootstrap-server

**Comment by yli-brex** [comment]
Hey @KaustubhKhati, thanks for sharing this for consumer. wonder could we support similar feature for producer?

**Comment by cchandurkar** [comment]
@yli-brex did you find solution for this? I'm looking for the same.
