### ISSUE TITLE
Support Optional headers in Kafka listener

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-kafka#51]
In HTTP controllers you can have `Optional`headers but trying the same with Kafka listeners gives an exception.

```
io.micronaut.core.bind.exceptions.UnsatisfiedArgumentException: Required argument [Optional color] not specified
	at io.micronaut.core.bind.DefaultExecutableBinder.bind(DefaultExecutableBinder.java:88)
	at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.lambda$process$7(KafkaConsumerProcessor.java:495)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Steps to Reproduce**

Create a listener with `Optional` header.

```
    @KafkaListener(offsetReset = OffsetReset.EARLIEST)
    @Topic("test")
    public static class TestListener {
        void receive(@KafkaKey String key, @Header String type, @Header Optional<String> color, String payload) {
            if (color.isPresent()) {
                // Works ok
            }
        }
    }
```
 
Send a message to the topic without the header (missing or null). 

**Expected Behaviour**

The optional header should be empty.

**Actual Behaviour**

The listener will not be invoked because it cannot bind header values.

**Environment Information**

Operating System: **MacOS 10.14.5**
Micronaut Version: **1.2.0.RC2**
JDK Version: **1.8.0**

**Example Application**

https://github.com/goeh/micronaut-kafka-optional-header-issue

**Comment by hmatt1** [comment]
Hi Göran,

I looked into this a bit, and I found another potential solution for your problem that supported with the current version of Micronaut.

Instead of using

```
void receive(@KafkaKey String key, @Header String type, @Header Optional<String> color, String payload) {
```

as your `receive` method signature, you can use

```
void receive(@KafkaKey String key, @Header String type, @Nullable @Header String color, String payload) {
```

The `@Nullable` annotation is supported for headers, so `color` will just be passed in as `null` instead of as an optional.

I will leave it up to Graeme if any changes are needed here, but there are styling discussions around whether passing `Optional`s as method arguments is a good practice:
https://stackoverflow.com/questions/31922866/why-should-java-8s-optional-not-be-used-in-arguments

I changed your test to this and it passes:

```
    @KafkaListener(offsetReset = OffsetReset.EARLIEST)
    @Topic(TOPIC)
    public static class TestListener {
        void receive(@KafkaKey String key, @Header String type, @Nullable @Header String color, String payload) {
            if (color != null) {
                latch1.countDown();
            } else {
                latch2.countDown();
            }
        }
    }
```

**Comment by goeh** [comment]
Thank you @hmatt1 for taking the time to look into this, but your solution with nullable is exactly what I currently use in all my listeners. My proposal was to align the Header handling in listeners with how it works in controllers (and all other components where headers are used in Micronaut). Making it work the same way everywhere eliminates developer confusion IMO.

**Comment by hmatt1** [comment]
@goeh that makes sense. I have opened https://github.com/micronaut-projects/micronaut-kafka/pull/53 as a potential fix

**Comment by goeh** [comment]
Thanks for the fix. I've verified (with Micronaut 1.2.6) that optional headers works ok in Kafka listeners.
