### ISSUE TITLE
Refactoring default producer and consumer factory

### ISSUE THREAD

**Issue by achatterjee104** [micronaut-projects/micronaut-kafka#527]
### Issue description

It will be good to refactore the default kafka producer and consumer factory classes so that the subclasses can customize the default behaviour of producer/consumer instance creation. For example, if the instantiation part of the producer/consumer is wrapped in single public/protected method (instead of calling "new" from 3 places in the KafkaProducerFactory class) then the subclasses can override the default logic as per their need - may be similar to Spring boot's DefaultKafkaProducerFactory. 

Also it will be nice to have an easy way replace the default beans because the below way does not replaces the default factory bean which I think it should as per the documentation.
`
@Factory
@Replaces(factory = KafkaProducerFactory.class)
class CustomFactory extends KafkaProducerFactory { 
   //custom code
}
` 

Please refer the [Stackoverflow Question](https://stackoverflow.com/questions/71604530/replacing-micronauts-default-kafkaproducerfactory-with-custom-factory-implement/71869954#71869954) for detailed context.

**Comment by graemerocher** [comment]
Fixed by https://github.com/micronaut-projects/micronaut-kafka/commit/245ce26c127c7f10feb05671b891afd91de6fa6c
