### ISSUE TITLE
Undocumented change (KafkaConsumerProcessor) breaks our ExceptionHandling

### ISSUE THREAD

**Issue by ckosmowski** [micronaut-projects/micronaut-kafka#588]
### Issue description

With this change here:

https://github.com/micronaut-projects/micronaut-kafka/commit/229bd9b3c1b6c73bc5739440b1fe4ebcac90a4f4#diff-12441f873cde9fb5329b119c0da6ea849dfa7cef2967c129a6bb476dd99dfa70L129-R129

the class KafkaConsumerProcessor got private and internal for no obvious reason. Also neither this breaking change itsself nor the maybe existing good reason for this was reflected in the release history or the documentation.

1.) Can someone clarify in which version of micronaut-bom we must expect this change? We went from 3.5.3 to 3.6.0 and got the problem. 

2.) This breaks all of our KafkaException handling because we used the KafkaConsumerProcessor to iterate consumers and to pause and resume them.

I even added the possibility to pause and resume single partitions instead of entire topics:
https://github.com/micronaut-projects/micronaut-kafka/commit/4b6a88fabeac5b16885a041c7d7cad59f3238e64

which was because we needed this feature (publically).

I am totally suprised about this change. Please revert or clarify / document a workaround on how to pause/resume consumers from Exception handlers

**Comment by ckosmowski** [comment]
Maybe @dstepanov has some information?

**Comment by dstepanov** [comment]
Those changes were done as part of Kafka 3 migration and expected to introduce breaking changes, it looks like the version bump got reverted but other changes remained.
You should be using `ConsumerRegistry` instead of `KafkaConsumerProcessor`.

**Comment by ckosmowski** [comment]
Great this should hopefully do it!
