### ISSUE TITLE
Array of kafka topic names in the configuration file.

### ISSUE THREAD

**Issue by Avbat** [micronaut-projects/micronaut-kafka#6]
When declaring an array of Kafka topic names, we get one string of names in @Topic(value) instead of the expected array of strings.

### Steps to Reproduce

1. In the configuration file we have the declared array of topics:
```
---
kafka:
...
  topics:
  - topic1
  - topic2
...
```

2. Declare the kafka listener:
```
@KafkaListener()
public class MessageListener {
  ...  
  @Topic("${kafka.topics}")
  public void receive(String message) {
  ...
  }
}
```

### Expected Behaviour

KafkaConsumerProcessor.process() line 273:
```
for (Topic topicAnnotation : topicAnnotations) {
  String[] topicNames = topicAnnotation.value(); // expected string array {"topic1", "topic2"}
```

### Actual Behaviour

KafkaConsumerProcessor.process() line 273:
```
for (Topic topicAnnotation : topicAnnotations) {
  String[] topicNames = topicAnnotation.value(); // get the string "topic1, topic2"
```

### Environment Information

- Micronaut Version: 1.0.2
- JDK Version: 1.8

**Comment by Bonythomasv** [comment]
@Avbat would you be able to share your sample project here,
cause i tried exact workaround that you suggested, but I'm getting this error at compile time.
` element value must be a constant expression`

    @Topic(patterns = "${kafka.topics}")

fun receive()

kafka:
  topics: topic1|topic2

@graemerocher do you have any suggestions to solve this issue?

**Comment by Bonythomasv** [comment]
Never mind, i got this working with this code
```
    @Topic(patterns = arrayOf("\${kafka.topics}"))
         fun receive()

`application.yml`
kafka:
  topics: topic1|topic2
```

**Comment by Bonythomasv** [comment]
@graemerocher do you think if there is any value in updating the documentation here:
https://micronaut-projects.github.io/micronaut-kafka/latest/guide/#kafkaListener

i can throw in PR if you like.

**Comment by guillermocalvo** [comment]
Duplicates https://github.com/micronaut-projects/micronaut-kafka/issues/26
Fixed by https://github.com/micronaut-projects/micronaut-kafka/pull/27
