### ISSUE TITLE
Kafka Listener committing whole batch on shutdown

### ISSUE THREAD

**Issue by PonzaMatteo** [micronaut-projects/micronaut-kafka#607]
### Expected Behavior

Offset for batches/records not processed should not be committed on application shutdown if the batches/records have not been successfully processed using offset `OffsetStrategy.SYNC`/`OffsetStrategy.SYNC_PER_RECORD`.

### Actual Behaviour

When the application shutdown while processing a batch of Kafka messages the offset for the entire batch is committed. 

This causes potential data loss since the messages not processed will be skipped entirely and I believe it is an unexpected behavior when using the offset strategies `OffsetStrategy.SYNC`/`OffsetStrategy.SYNC_PER_RECORD`.

### Steps To Reproduce

- create kafka topic
- add several messages to that topic
- start up kafka consumer application
- shutdown the application before all the messages have been processed
- verify that the offset committed is for a whole batch and some messages have been skipped

### Environment Information

- micronaut kafa: v4.4.1

I believe the issue is with the [logic](https://github.com/micronaut-projects/micronaut-kafka/blob/master/kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java#L485):

```kotlin
  } catch (WakeupException e) {
      try {
          if (!failed && consumerState.offsetStrategy != OffsetStrategy.DISABLED) {
              kafkaConsumer.commitSync();
          }
```
Not sure if in that part we should commit to the offset, given that there is no guarantee that those messages have been processed.

### Version

micronaut kafa: v4.4.1

**Comment by graemerocher** [comment]
Would you like to send a PR?

**Comment by graemerocher** [comment]
Might be resolved with https://github.com/micronaut-projects/micronaut-kafka/issues/601

**Comment by PonzaMatteo** [comment]
> Would you like to send a PR?

I'll take a look in the coming days. My approach would probably be something like:
- [initialize ](https://github.com/micronaut-projects/micronaut-kafka/blob/f453189be49389084eeee04c568f9569cd700f3a/kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java#L458)  `failed` to true, so by default it won't commit the whole batch of it didn't finished processing.

**Comment by PonzaMatteo** [comment]
I tried to address the issue, here's the PR
- https://github.com/micronaut-projects/micronaut-kafka/pull/615

I see that it has been added to the [new release](https://github.com/micronaut-projects/micronaut-kafka/pull/615#event-7814790900). 

Not sure if it can be helpful but here I added a sample app that can help to re-produce the issue outside the test environment:
- https://github.com/PonzaMatteo/micronaut-kafka-issue-commit-batch-shutdown
