### ISSUE TITLE
Message loss with `ErrorStrategyValue.RETRY_ON_ERROR`

### ISSUE THREAD

**Issue by misogl** [micronaut-projects/micronaut-kafka#629]
### Expected Behavior

When an exception is thrown inside the `receive` method and `errorStrategy` is set to `RETRY_ON_ERROR`, the offset is reset back to the problematic message (by calling `kafkaConsumer.seek(topicPartition, consumerRecord.offset())`) and the processing of the entire batch is terminated by returning `false` from this block:
```java
            } catch (Throwable e) {
                if (resolveWithErrorStrategy(consumerState, consumerRecord, e)) {
                    return false;
                }
            }
```

### Actual Behaviour

The issue is that the batch can contain messages from other partitions that are just ignored - there is no offset reset for unprocessed messages from these partitions.
Next call to `kafkaConsumer.poll(pollTimeout)` does return the problematic message but not the other unprocessed messages that were already polled in the previous call.

I have tried to set the `offsetStrategy` to `SYNC`, `ASYNC`, `SYNC_PER_RECORD`, and `ASYNC_PER_RECORD` but it did not make any difference.

The only workaround is to set `MAX_POLL_RECORDS_CONFIG` property to `1` so only a single message is returned from `kafkaConsumer.poll()` call.

### Steps To Reproduce

1. Create a topic with multiple partitions
2. Publish messages to different partitions
3. Create a listener to process messages from this topic
4. Throw an exception when processing the first message in the `receive` method
5. Multiple messages from other partitions are skipped - this depends on the `MAX_POLL_RECORDS_CONFIG` property

### Version

4.5.0

**Comment by misogl** [comment]
I have created a standalone test that replicates this issue: https://github.com/misogl/micronaut-kafka-issue-629

**Comment by graemerocher** [comment]
would you like to send a PR?
