### ISSUE TITLE
Custom timestamp for ProducerRecord

### ISSUE THREAD

**Issue by finke-ba** [micronaut-projects/micronaut-kafka#63]
Hello,

I'm trying to provide my custom timestamp value for the KafkaClient. 
But it can't be done since it is just a boolean flag and in `KafkaClientIntroductionAdvice.buildProducerRecord` it's just a ternary operator with `System.currentTimeMillis()` or `null`:
```
private ProducerRecord buildProducerRecord(AnnotationValue<KafkaClient> client, String topic, List<Header> kafkaHeaders, Object key, Object value) {
    return new ProducerRecord(
            topic,
            null,
            client.getRequiredValue("timestamp", Boolean.class) ? System.currentTimeMillis() : null,
            key,
            value,
            kafkaHeaders.isEmpty() ? null : kafkaHeaders
    );
}
```
I would like to add support for this, probably by adding new annotation like @KafkaKey.
How does that sound to you?

**Comment by graemerocher** [comment]
Sounds good. Contributions are welcome
