### ISSUE TITLE
Not able to get Kafka metrics when enabled

### ISSUE THREAD

**Issue by pmmerchant** [micronaut-projects/micronaut-kafka#634]
### Expected Behavior

Enabled Kafka via configuration micronaut.metrics.binders.kafka.enabled : true.

Get Kafka metrics via Micrometer via scrape method from PrometheusMeterRegistry.

The expected behavior was to get lag related data from kafka_consumer_records_lag metric. 

### Actual Behaviour

kafka_consumer_records_lag records are 0 or Nan

### Steps To Reproduce

Enable kafka by setting micronaut.metrics.binders.kafka.enabled to true

Get metrics via micrometer PrometheusMeterRegistry

### Environment Information

JAVA 11

### Version

3.7.3

**Comment by guillermocalvo** [comment]
@pmmerchant 

Please note that `kafka_consumer_records_lag_records` represents the current number of records that haven't been consumed yet.

In healthy scenarios, this should tend to zero. An increasing value over time indicates that the consumer group is not keeping up with the producers.

I wanted to make sure that Kafka metrics are being reported properly, so I made a simple test and created a consumer that generates two records every time a record is received:

```java
@KafkaListener(clientId = "foobar", offsetReset = OffsetReset.EARLIEST)
public class MyConsumer {

    @Inject
    MyProducer producer;

    @Topic("foo")
    public void consume(String event) {
        producer.produce("ONE");
        producer.produce("TWO");
    }

    @KafkaClient
    public interface MyProducer {
        @Topic("foo")
        void produce(String message);
    }
}
```

Then I checked `/prometheus` and I confirmed that these metrics were growing over time:

```
kafka_consumer_records_lag_records{client_id="foobar",partition="0",topic="foo",} 4784.0
kafka_consumer_records_lag_max_records{client_id="foobar",} 5784.0
kafka_consumer_records_lag_avg_records{client_id="foobar",partition="0",topic="foo",} 713.6666666666666
```

Therefore I think Kafka metrics are working as expected.

I will close this ticket now. Please feel free to reopen it if you still think something needs to be fixed.
