### ISSUE TITLE
JsonObjectSerde is internal?

### ISSUE THREAD

**Issue by henriquelsmti** [micronaut-projects/micronaut-kafka#637]
### Issue description

The class  io.micronaut.configuration.kafka.serde.JsonObjectSerde is notated with @Internal, 
but in the documentation it says that I can use and extend.
https://micronaut-projects.github.io/micronaut-kafka/latest/guide/
![image](https://user-images.githubusercontent.com/9632578/207323389-27d478ab-047b-4498-a145-65c62163792f.png)

Currently I am using this class as a source of kafka streams, after I updated to the latest version it started throwing warnings in the compilation.

**Comment by yawkat** [comment]
not really, it was made internal in #554 but we can probably revert it
