### ISSUE TITLE
Messages not reprocessed by consumer when SerializationException occurs while producing message

### ISSUE THREAD

**Issue by larsduelfer** [micronaut-projects/micronaut-kafka#640]
### Expected Behavior

I am using a KafkaListener that sends transformed messages via `@SendTo` to another topic. I am using `OffsetStrategy.SEND_TO_TRANSACTION` as well as the error strategy `RETRY_ON_ERROR` and I configured the producer as a transactional one. When a `SerializationException` occurs (e.g. Schema Registry not available), I expect that the message is retried as also happens when other exceptions occur in the listener.

### Actual Behaviour

Without any further configuration, the message is skipped (default behaviour of DefaultKafkaListenerExceptionHandler) and the next message is processed. In case this succeeds, the offset is committed via the producer and the failed message is skipped without processing.

As stated above, the expected behaviour is that those errors are also triggering a retry as other consumer errors do as well. 

**Workaround for now:** I replaced the bean `DefaultKafkaListenerExceptionHandler` with a custom one that seeks to the current offset instead of seeking to the next offset. However, this does not respect the retry back off configuration from the ErrorStrategy since it is not available there.

### Version

4.5.0

**Comment by larsduelfer** [comment]
Looking deeper into the code I assume that changing towards a consistent retry behaviour requires quite some refactoring. Errors that happen when producing a message as a consequence of using the `@SendTo `annotation on fhe kafka listener method call the configured exception handler bean (as stated above) whereas exceptions that occur as part of the kafka listener method execution are handled by the framework class `KafkaConsumerProcessor`.

Any thoughts on this?

**Comment by jeremyg484** [comment]
@guillermocalvo Note that I think this is related to the core issue discussed in #110 (see the conversation there for the full context - the title is misleading).
