### ISSUE TITLE
Unable to use topology optimization in Micronaut v1.2

### ISSUE THREAD

**Issue by jgray1206** [micronaut-projects/micronaut-kafka#65]
With the recent upgrade to using Kafka 2.3.0, there was a missed breaking change in the Streams API. They have changed how to enable topology optimization.

`As of 2.3.0 we've updated how to turn on optimizations. Now, to enable optimizations, you need to do two things. First, add this line to your properties, properties.setProperty(StreamsConfig.TOPOLOGY_OPTIMIZATION, StreamsConfig.OPTIMIZE);, as you have done before. Second, when constructing your KafkaStreams instance, you'll need to pass your configuration properties when building your topology by using the overloaded StreamsBuilder.build(Properties) method. For example, KafkaStreams myStream = new KafkaStreams(streamsBuilder.build(properties), properties).`

For topology optimization to work, the “using the overloaded streamsBuilder method” thing will have to be implemented.

**Comment by graemerocher** [comment]
So this is for the case where you set `TOPOLOGY_OPTIMIZATION` in configuration right?

**Comment by jgray1206** [comment]
Correct! It defaults to “none”. So it only really needs to use the overloaded streamsBuilder.build method when someone sets that property to “all”.

**Comment by graemerocher** [comment]
Gotcha

**Comment by Sabst** [comment]
With this change: https://github.com/micronaut-projects/micronaut-kafka/commit/007032ea807c368611ff2211daea7db87d1672de#diff-dbe96e363bc872988919e2c70002eb93L68

I now get:
```
Caused by: java.lang.NoSuchMethodError: io.micronaut.configuration.kafka.streams.ConfiguredStreamBuilder.build(Ljava/util/Properties;)Lorg/apache/kafka/streams/Topology;
	at io.micronaut.configuration.kafka.streams.KafkaStreamsFactory.kafkaStreams(KafkaStreamsFactory.java:68)
	at io.micronaut.configuration.kafka.streams.$KafkaStreamsFactory$KafkaStreams1Definition.build(Unknown Source)
	at io.micronaut.context.BeanDefinitionDelegate.build(BeanDefinitionDelegate.java:205)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1535)
```

Can you please check?

**Comment by jgray1206** [comment]
It’ll only work when you are pulling in Kafka 2.3.0. Are you overriding the version of Kafka that Micronaut Kafka pulls in?

**Comment by Sabst** [comment]
Here is my gradle.properties file (from the master branch, nothing changed apart from the micronaut version):
```
projectVersion=1.2.1.BUILD-SNAPSHOT
kafkaVersion=2.3.0
micronautDocsVersion=1.0.3
micronautVersion=1.2.0
micronautTestVersion=1.0.4
protocVersion=3.5.1
groovyVersion=2.5.6
title=Micronaut Kafka
projectDesc=Integration between Micronaut and Kafka Messaging
projectUrl=http://micronaut.io
githubSlug=micronaut-projects/micronaut-kafka
githubBranch=master
spockVersion=1.2-groovy-2.5
developers=Graeme Rocher
# Needed for documentation generation. Needs to be Grails 3.2.x not 3.3.x
grailsVersion=3.2.9
testskafka=kafka/src/test/groovy/io/micronaut/configuration/kafka/docs
testskafkastreams=kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams
kafkastreams=kafka-streams/src/main/groovy/io/micronaut/configuration/kafka/streams
```
So Kafka 2.3.0 is used in this case, right?
