### ISSUE TITLE
Is there any way to set KafkaListener.threads() using config?

### ISSUE THREAD

**Issue by brunodomenici** [micronaut-projects/micronaut-kafka#689]
### Issue description

Hello,

Today I'm setting my consumer threads using KafkaListerner Annotation:

```java
@KafkaListener(groupId = "${audit-log.group-id}", offsetReset = OffsetReset.EARLIEST, threads =  3)
```

I'd like to put threads in my config (as I do with groupId) but thread is `int` so I can't use placeholder there.

Any recommendation in how to do it?

Thank you

**Comment by PonzaMatteo** [comment]
This option would be really useful for our use cases as well (applications in different environments have different scalability needs).
