### ISSUE TITLE
ClusterAuthorizationException

### ISSUE THREAD

**Issue by sabithasekar** [micronaut-projects/micronaut-kafka#752]
### Issue description

I'm trying to connect to Confluent kafka from my micronaut java 17 application . 

Error log
17:30:21.904 [kafka-admin-client-thread | adminclient-1] ERROR i.m.m.health.indicator.HealthResult - Health indicator [kafka] reported exception: org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.
org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.
17:31:15.843 [kafka-admin-client-thread | adminclient-1] ERROR i.m.m.health.indicator.HealthResult - Health indicator [kafka] reported exception: org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.

Can someone help on this

**Comment by sdelamo** [comment]
seems related to https://github.com/micronaut-projects/micronaut-kafka/pull/774

**Comment by sdelamo** [comment]
@sabithasekar are you using Micronaut Framework 3 or Micronaut Framework 4?

**Comment by guillermocalvo** [comment]
Hi @sabithasekar

Micronaut Kafka version 5.0.2 was published recently. This release should hopefully fix your problem. Could you try running your application with the latest version of the library? Please feel free to reopen this issue in case it's still failing. Thanks!
