### ISSUE TITLE
Control over the start of Kafka Streams

### ISSUE THREAD

**Issue by mzuber88** [micronaut-projects/micronaut-kafka#79]
Is there a way to control the starting of Kafka streams in micronaut? I've followed the examples in the documentation and have a Stream Class like this:

```
@Factory
public class MyStreamer {

    @Singleton
    @Named("my-streamer")
    KStream<String, String> myStreamFunc(ConfiguredStreamBuilder builder)

```

It seems that as soon as the application starts it will create the consumer and producers and link them to the topics specified in myStreamFunc and if there is data in the topics (say from a previous run of the app) it will start consuming that data.

Mainly I want to control this behavior, I don't want the stream application to automatically start pulling data on startup until I say so.  I think basically I want control over streams.start() which is hidden inside the micronaut kafka code as far as I can tell.

It seems with regular consumers there is more control like you can use the ConsumerRegistry to pause and resume consumers, but the consumers created by kafka streams don't seem to even show up in the registry.

**Comment by graemerocher** [comment]
This is currently done here https://github.com/micronaut-projects/micronaut-kafka/blob/3a8a7c5dca422876131186b29120c6e250237bb5/kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/KafkaStreamsFactory.java#L72

I think how this could be made it work is via events that you could hook into, although these are not implemented yet. Maybe we need `KafkaStartEvent` and `KafkaStopEvent` or some such events you could write listeners for.

Seems like it would be a good feature to contribute if you are interested.

**Comment by graemerocher** [comment]
Duplicate  #92
