### ISSUE TITLE
micronaut kafka 1.3.0.x listeners are broken

### ISSUE THREAD

**Issue by dancegit** [micronaut-projects/micronaut-kafka#87]
Create a micronaut kafka project with and add a producer for a topic
Produce records and verify that they appear with the kafka console ('kafka-console-consumer.sh')
Create a micronaut kafka project with 1.3.0.m2 and add a listener to the topic
Run the listener app-> it does not receive anything
Change micronaut-version from 1.3.0.m2 to 1.2.6, rerun the listner app, now it receives/parses the records

Also: the 'Body' and 'Header' annotations are not included in 1.3.0.x .. seems the classes are not included in the build.. :/

**Comment by Sabst** [comment]
Please check if the comment I added today to #83 helps

**Comment by dancegit** [comment]
implementation "io.micronaut:micronaut-messaging:1.3.0.M2"  as dependency solves the problem

**Comment by graemerocher** [comment]
Interesting. @dancegit thanks for the hint will take a closer look and do another release possibly with upgrading to Kafka 2.4
