### ISSUE TITLE
JsonSerde does not support deserialization of message with no body

### ISSUE THREAD

**Issue by dfeist** [micronaut-projects/micronaut-kafka#88]
Serialization with Jackson fails with a `SerializationException` if a received Kafka message does not have a  body.  This means that it is not possible to subscribe to a compacted topic that uses tombstone messages without failures.  JsonSerde should deal with this by checking for null/empty byte[] before attempting deserialization.

**Comment by graemerocher** [comment]
Thanks for the PR
