### ISSUE TITLE
KafkaStreams Cleanup call

### ISSUE THREAD

**Issue by titaniumcoder** [micronaut-projects/micronaut-kafka#92]
For resetting kafka streams correctly, the application would need to call the kafkaStreams.cleanup() method (see also here: https://www.confluent.io/blog/data-reprocessing-with-kafka-streams-resetting-a-streams-application/ ). I assume it would need to be done just before the start in this line:

https://github.com/micronaut-projects/micronaut-kafka/blob/3a8a7c5dca422876131186b29120c6e250237bb5/kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/KafkaStreamsFactory.java#L72

But I am not sure what would be the best way to implement something like this. It doesn't make really sense to do it on all startups, but rather somehow via configuration (system property?). Is there a best way to do something like that in Micronaut? I guess some kind of event "Kafka Streams Prepared" or so would be a nice option but not sure if that's the best way.

**Comment by graemerocher** [comment]
Micronaut Kafka now supports 2 new events: `BeforeKafkaStreamStart` and `AfterKafkaStreamStart` to address this

See https://github.com/micronaut-projects/micronaut-kafka/blob/8ecc4d00dfd39d3b5e5c5ef75cb884db80ba7f3e/kafka-streams/src/test/groovy/io/micronaut/configuration/kafka/streams/listeners/BeforeStartKafkaStreamsListenerImp.java for an example
